### ISSUE TITLE
good slicer

### ISSUE THREAD

**Issue by Tempesting** [asmorgan24/pngSlicer#1]
It's quite convenient and useful for me to find the code here.I can easily build and run it to slice my stl file.
But i find it useless to adjust the resolution of Z axis,so i can only get a fixed number of slices.It's a small problem foe me because it is sufficient for me.
It will be better if I can adjust the resolution of output images without cutting them.

**Comment by asmorgan24** [comment]
Hello!

Thanks for your interest. I am a little confused by what you mean. Are you
looking for a specific layer height? In that case, set the resolution
according to the (max_z-min_z)/layer_height to get the resolution you want
with the correct number of slices. I never actually used this on a printer,
so I didn't get around to developing this too far. I hope this helps!

**Comment by asmorgan24** [comment]
closing
