### ISSUE TITLE
Confused about some parameters used

### ISSUE THREAD

**Issue by zakiakhatun21** [asmorgan24/pngSlicer#5]
Hello Mr. Andrew Morgan,

I am not very familiar with STL files. But I have an STL file which I don't need for my project, instead I need a PNG file as a segmentation mask. Using your code it works but since I didn't understand some of the parameters used from your code I didn't get the expected result.
1. My original 3D data shape is **256 * 256 * 192** and the pixel spacing is **0.58 * 0.58 * 0.6**. I want my STL file to generate **192** PNG files.
In your code, **default_resolution** = 0.05, **scale** = 20 and **add_vertex** = Vector3 (0.5,0.5,0.5).
Could you kindly say, based on my case, which values ​​should I use?

*(I ran your code using res = 0.6, add_vertex = Vector3 (0.58, 0.58, 0.6) and scale = 20, it produced 75 png files (1.png, 12.png, 23.png.......). But I need 192 files, not 75. I'm definitely doing something wrong because I'm not quite sure about the usage and applications of the three mentioned parameters.

It would be great to hear back from you. Thanks.

**Comment by asmorgan24** [comment]
Hello,

I spent some time today editing the repo, so please pull once again. The
resolution parameter now works, in addition to the scaling parameter (at
least they are correct now). The height and width parameters are still
weird--I will need to work on those at some later time. Realistically, it
should produce the correct images now on a 2000x2000 pixel image. If you
change this aspect ratio, e.g. to 2000x1800, you will likely see some sort
of warping. I need to figure that out eventually. I am pretty sure it has
to do with the coordinate system of the image.

Cheers,
Andy
